name: CI

on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: 21
            distribution: "temurin"
            cache: gradle

      - name: Deploy infrastructure
        run: docker-compose -f compose.yaml up -d

      - name: Build Application
        run: ./gradlew build

      - name: Run deltaCoverage
        run: ./gradlew deltaCoverage

      - name: Destroy infrastructure
        if: always()
        run: docker-compose -f compose.yaml down
